version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"

  database:
    image: postgres:13.4
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc
      - POSTGRES_DB=td_1